Add persistence and logout redirect uri
alexandrtovmach/react-microsoft-login pull request #79
Opened 2021-04-05 15:45 UTC by FranCarstens

This merge includes the following changes:

1. Addition of `postLogoutRedirectUri` as documented on [Single-page application: Sign-in and Sign-out](https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-spa-sign-in?tabs=javascript2)
2. Addition of `useLocalStorageCache` as documented on [More about SSO with MSAL](https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-js-sso)
3. Typo corrections of `Exaple` to `Example` in Readme and example files.
4. Updated Readme to include new properties `postLogoutRedirectUri` and `useLocalStorageCache`.

2021-05-10 14:34 UTC, alexandrtovmach requested changes
Looks amazing, just one suggestion to improve. We should keep flexibility, and do not force redirect flow if it's possible to stay on page.

2021-05-10 14:34 UTC, alexandrtovmach commented on src/MicrosoftLogin.tsx
> +    clientToken && getGraphAPITokenAndUser(true);
```suggestion
    clientToken && getGraphAPITokenAndUser(forceRedirectStrategy || checkToIE());
```

2021-05-10 14:36 UTC, alexandrtovmach commented
@FranCarstens Thanks for contribution :muscle: Seems really useful improvement

Could you check requested changes and let me know what do you think?

2021-05-13 04:05 UTC, alexandrtovmach commented
@FranCarstens Could you?)

2021-05-28 15:00 UTC, FranCarstens commented
That looks great. Sorry for the late reply :)

2021-05-28 15:02 UTC, alexandrtovmach approved these changes

2021-05-28 15:02 UTC, merged

2021-05-28 15:03 UTC, alexandrtovmach commented
@FranCarstens thanks for contribution
Updates will be available in 1.15.0

2021-05-28 15:07 UTC, alexandrtovmach commented
Done:
https://www.npmjs.com/package/react-microsoft-login/v/1.15.0